// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTp1xB9bYCAExNDrPl7G3K812gDcKI_c',
    appId: '1:880519522381:web:8a81d92b374292c28a5404',
    messagingSenderId: '880519522381',
    projectId: 'm-m-b-6cf84',
    authDomain: 'm-m-b-6cf84.firebaseapp.com',
    storageBucket: 'm-m-b-6cf84.firebasestorage.app',
    measurementId: 'G-DB8SKP6HRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNCpAY16JffiH1I11KXrL-xECHM-eLEAU',
    appId: '1:880519522381:android:527403c9e96922048a5404',
    messagingSenderId: '880519522381',
    projectId: 'm-m-b-6cf84',
    storageBucket: 'm-m-b-6cf84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEYnscP4WBToQVbexH1PtZYrgF7Sd-RH0',
    appId: '1:880519522381:ios:cca01f786bf0096e8a5404',
    messagingSenderId: '880519522381',
    projectId: 'm-m-b-6cf84',
    storageBucket: 'm-m-b-6cf84.firebasestorage.app',
    iosBundleId: 'com.mmb.techzone',
  );
}
